/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "communicate.h"
#ifndef _KERNEL
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#endif /* !_KERNEL */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

bool_t *
ping_203(clnt)
	CLIENT *clnt;
{
	static bool_t clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	 if (clnt_call(clnt, ping,
		(xdrproc_t)xdr_void, NULL,
		(xdrproc_t)xdr_bool, (caddr_t)&clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
join_203(IP, Port, clnt)
	char *IP;
	int Port;
	CLIENT *clnt;
{
	join_203_argument arg;
	static bool_t clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	if (clnt_call(clnt, join,
		(xdrproc_t)xdr_join_203_argument, (caddr_t)&arg,
		(xdrproc_t)xdr_bool, (caddr_t)&clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
leave_203(IP, Port, clnt)
	char *IP;
	int Port;
	CLIENT *clnt;
{
	leave_203_argument arg;
	static bool_t clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	if (clnt_call(clnt, leave,
		(xdrproc_t)xdr_leave_203_argument, (caddr_t)&arg,
		(xdrproc_t)xdr_bool, (caddr_t)&clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
subscribe_203(IP, Port, Article, clnt)
	char *IP;
	int Port;
	char *Article;
	CLIENT *clnt;
{
	subscribe_203_argument arg;
	static bool_t clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	arg.Article = Article;
	if (clnt_call(clnt, subscribe,
		(xdrproc_t)xdr_subscribe_203_argument, (caddr_t)&arg,
		(xdrproc_t)xdr_bool, (caddr_t)&clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
unsubscribe_203(IP, Port, Article, clnt)
	char *IP;
	int Port;
	char *Article;
	CLIENT *clnt;
{
	unsubscribe_203_argument arg;
	static bool_t clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	arg.Article = Article;
	if (clnt_call(clnt, unsubscribe,
		(xdrproc_t)xdr_unsubscribe_203_argument, (caddr_t)&arg,
		(xdrproc_t)xdr_bool, (caddr_t)&clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
publish_203(IP, Port, Article, clnt)
	char *IP;
	int Port;
	char *Article;
	CLIENT *clnt;
{
	publish_203_argument arg;
	static bool_t clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	arg.Article = Article;
	if (clnt_call(clnt, publish,
		(xdrproc_t)xdr_publish_203_argument, (caddr_t)&arg,
		(xdrproc_t)xdr_bool, (caddr_t)&clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
update_203(IP, Port, clnt)
	char *IP;
	int Port;
	CLIENT *clnt;
{
	update_203_argument arg;
	static bool_t clnt_res;

	(void) memset(&clnt_res, 0, sizeof (clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	if (clnt_call(clnt, update,
		(xdrproc_t)xdr_update_203_argument, (caddr_t)&arg,
		(xdrproc_t)xdr_bool, (caddr_t)&clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
