/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "communicate.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <memory.h>
#include <stropts.h>
#include <netconfig.h>
#include <sys/resource.h> /* rlimit */
#include <syslog.h>

#ifdef DEBUG
#define	RPC_SVC_FG
#endif

#define	_RPCSVC_CLOSEDOWN 120
static int _rpcpmstart;		/* Started by a port monitor ? */

/* States a server can be in wrt request */

#define	_IDLE 0
#define	_SERVED 1

static int _rpcsvcstate = _IDLE;	/* Set when a request is serviced */
static int _rpcsvccount = 0;		/* Number of requests being serviced */

#if	defined(RPC_MSGOUT)
extern void RPC_MSGOUT();
#else	/* defined(RPC_MSGOUT) */
static void
RPC_MSGOUT(fmt, msg)
	char *fmt;
	char *msg;
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, fmt, msg);
	else {
		(void) fprintf(stderr, fmt, msg);
		(void) putc('\n', stderr);
	}
#else
	syslog(LOG_ERR, fmt, msg);
#endif
}
#endif	/* defined(RPC_MSGOUT) */

static void
closedown(sig)
	int sig;
{
	if (_rpcsvcstate == _IDLE && _rpcsvccount == 0) {
		int size;
		int i, openfd = 0;

		size = svc_max_pollfd;
		for (i = 0; i < size && openfd < 2; i++)
			if (svc_pollfd[i].fd >= 0)
				openfd++;
		if (openfd <= 1)
			exit(0);
	} else
		_rpcsvcstate = _IDLE;

	(void) signal(SIGALRM, (void(*)()) closedown);
	(void) alarm(_RPCSVC_CLOSEDOWN/2);
}

/* ARGSUSED */
static bool_t *
_ping_203(argp, rqstp)
	void  *argp;
	struct svc_req *rqstp;
{
	return (ping_203(rqstp));
}

static bool_t *
_join_203(argp, rqstp)
	join_203_argument *argp;
	struct svc_req *rqstp;
{
	return (join_203(
	    argp->IP,
	    argp->Port,
	    rqstp));
}

static bool_t *
_leave_203(argp, rqstp)
	leave_203_argument *argp;
	struct svc_req *rqstp;
{
	return (leave_203(
	    argp->IP,
	    argp->Port,
	    rqstp));
}

static bool_t *
_subscribe_203(argp, rqstp)
	subscribe_203_argument *argp;
	struct svc_req *rqstp;
{
	return (subscribe_203(
	    argp->IP,
	    argp->Port,
	    argp->Article,
	    rqstp));
}

static bool_t *
_unsubscribe_203(argp, rqstp)
	unsubscribe_203_argument *argp;
	struct svc_req *rqstp;
{
	return (unsubscribe_203(
	    argp->IP,
	    argp->Port,
	    argp->Article,
	    rqstp));
}

static bool_t *
_publish_203(argp, rqstp)
	publish_203_argument *argp;
	struct svc_req *rqstp;
{
	return (publish_203(
	    argp->IP,
	    argp->Port,
	    argp->Article,
	    rqstp));
}

static bool_t *
_update_203(argp, rqstp)
	update_203_argument *argp;
	struct svc_req *rqstp;
{
	return (update_203(
	    argp->IP,
	    argp->Port,
	    rqstp));
}

static void
communicate_prog_203(rqstp, transp)
	struct svc_req *rqstp;
	register SVCXPRT *transp;
{
	union {
		join_203_argument join_203_arg;
		leave_203_argument leave_203_arg;
		subscribe_203_argument subscribe_203_arg;
		unsubscribe_203_argument unsubscribe_203_arg;
		publish_203_argument publish_203_arg;
		update_203_argument update_203_arg;
	} argument;
	char *result;
	bool_t (*_xdr_argument)(), (*_xdr_result)();
	char *(*local)();

	_rpcsvccount++;
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, xdr_void,
			NULL);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return; /* CSTYLED */

	case ping:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_bool;
		local = (char *(*)())
		    _ping_203;
		break;

	case join:
		_xdr_argument = xdr_join_203_argument;
		_xdr_result = xdr_bool;
		local = (char *(*)())
		    _join_203;
		break;

	case leave:
		_xdr_argument = xdr_leave_203_argument;
		_xdr_result = xdr_bool;
		local = (char *(*)())
		    _leave_203;
		break;

	case subscribe:
		_xdr_argument = xdr_subscribe_203_argument;
		_xdr_result = xdr_bool;
		local = (char *(*)())
		    _subscribe_203;
		break;

	case unsubscribe:
		_xdr_argument = xdr_unsubscribe_203_argument;
		_xdr_result = xdr_bool;
		local = (char *(*)())
		    _unsubscribe_203;
		break;

	case publish:
		_xdr_argument = xdr_publish_203_argument;
		_xdr_result = xdr_bool;
		local = (char *(*)())
		    _publish_203;
		break;

	case update:
		_xdr_argument = xdr_update_203_argument;
		_xdr_result = xdr_bool;
		local = (char *(*)())
		    _update_203;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return; /* CSTYLED */
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, _xdr_argument, (caddr_t)&argument)) {
		svcerr_decode(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return; /* CSTYLED */
	}
	result = (*local)(&argument, rqstp);
	if (_xdr_result && result != NULL &&
	    !svc_sendreply(transp, _xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, _xdr_argument, (caddr_t)&argument)) {
		RPC_MSGOUT("%s",
		    "unable to free arguments");
		exit(1);
	}
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	return; /* CSTYLED */
}

int
main()
{
	pid_t pid;
	int i;

	(void) sigset(SIGPIPE, SIG_IGN);

	/*
	 * If stdin looks like a TLI endpoint, we assume
	 * that we were started by a port monitor. If
	 * t_getstate fails with TBADF, this is not a
	 * TLI endpoint.
	 */
	if (t_getstate(0) != -1 || t_errno != TBADF) {
		char *netid;
		struct netconfig *nconf = NULL;
		SVCXPRT *transp;
		int pmclose;

		_rpcpmstart = 1;
		openlog("communicate", LOG_PID, LOG_DAEMON);

		if ((netid = getenv("NLSPROVIDER")) == NULL) {
		/* started from inetd */
			pmclose = 1;
		} else {
			if ((nconf = getnetconfigent(netid)) == NULL)
				RPC_MSGOUT("%s",
				    "cannot get transport info");

			pmclose = (t_getstate(0) != T_DATAXFER);
		}
		if ((transp = svc_tli_create(0, nconf, NULL, 0, 0)) == NULL) {
			RPC_MSGOUT("%s",
			    "cannot create server handle");
			exit(1);
		}
		if (nconf)
			freenetconfigent(nconf);
		if (!svc_reg(transp, COMMUNICATE_PROG, COMMUNICATE_VERSION,
		    communicate_prog_203, 0)) {
			RPC_MSGOUT("%s",
			    "unable to register (COMMUNICATE_PROG, COMMUNICATE_VERSION).");
			exit(1);
		}
		if (pmclose) {
			(void) signal(SIGALRM, (void(*)()) closedown);
			(void) alarm(_RPCSVC_CLOSEDOWN/2);
		}
		svc_run();
		exit(1);
		/* NOTREACHED */
	}	else {
#ifndef RPC_SVC_FG
#pragma weak closefrom
		extern void closefrom(int);
		int size;
		struct rlimit rl;
		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			exit(1);
		}
		if (pid)
			exit(0);
		if (closefrom != NULL)
			closefrom(0);
		else {
			rl.rlim_max = 0;
			getrlimit(RLIMIT_NOFILE, &rl);
			if ((size = rl.rlim_max) == 0)
				exit(1);
			for (i = 0; i < size; i++)
				(void) close(i);
		}
		i = open("/dev/null", 2);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		setsid();
		openlog("communicate", LOG_PID, LOG_DAEMON);
#endif
	}
	if (!svc_create(
	    communicate_prog_203, COMMUNICATE_PROG, COMMUNICATE_VERSION,
	    "netpath")) {
		RPC_MSGOUT("%s",
		    "unable to create (COMMUNICATE_PROG, COMMUNICATE_VERSION) for netpath.");
		exit(1);
	}

	svc_run();
	RPC_MSGOUT("%s",
	    "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
