/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "communicate.h"

#ifndef _KERNEL
#include <stdlib.h>
#endif /* !_KERNEL */


bool_t
xdr_join_203_argument(xdrs, objp)
	XDR *xdrs;
	join_203_argument *objp;
{

	if (!xdr_string(xdrs, &objp->IP, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->Port))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_leave_203_argument(xdrs, objp)
	XDR *xdrs;
	leave_203_argument *objp;
{

	if (!xdr_string(xdrs, &objp->IP, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->Port))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_subscribe_203_argument(xdrs, objp)
	XDR *xdrs;
	subscribe_203_argument *objp;
{

	if (!xdr_string(xdrs, &objp->IP, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->Port))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->Article, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_unsubscribe_203_argument(xdrs, objp)
	XDR *xdrs;
	unsubscribe_203_argument *objp;
{

	if (!xdr_string(xdrs, &objp->IP, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->Port))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->Article, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_publish_203_argument(xdrs, objp)
	XDR *xdrs;
	publish_203_argument *objp;
{

	if (!xdr_string(xdrs, &objp->IP, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->Port))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->Article, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_update_203_argument(xdrs, objp)
	XDR *xdrs;
	update_203_argument *objp;
{

	if (!xdr_string(xdrs, &objp->IP, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->Port))
		return (FALSE);
	return (TRUE);
}
