/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMMUNICATE_H_RPCGEN
#define	_COMMUNICATE_H_RPCGEN

#include <rpc/rpc.h>

struct join_203_argument {
	char *IP;
	int Port;
};
typedef struct join_203_argument join_203_argument;

struct leave_203_argument {
	char *IP;
	int Port;
};
typedef struct leave_203_argument leave_203_argument;

struct subscribe_203_argument {
	char *IP;
	int Port;
	char *Article;
};
typedef struct subscribe_203_argument subscribe_203_argument;

struct unsubscribe_203_argument {
	char *IP;
	int Port;
	char *Article;
};
typedef struct unsubscribe_203_argument unsubscribe_203_argument;

struct publish_203_argument {
	char *IP;
	int Port;
	char *Article;
};
typedef struct publish_203_argument publish_203_argument;

struct update_203_argument {
	char *IP;
	int Port;
};
typedef struct update_203_argument update_203_argument;

#define	COMMUNICATE_PROG	0x20000001
#define	COMMUNICATE_VERSION	203
#define	ping	1
extern  bool_t * ping_203();
#define	join	2
extern  bool_t * join_203();
#define	leave	3
extern  bool_t * leave_203();
#define	subscribe	4
extern  bool_t * subscribe_203();
#define	unsubscribe	5
extern  bool_t * unsubscribe_203();
#define	publish	6
extern  bool_t * publish_203();
#define	update	7
extern  bool_t * update_203();
extern int communicate_prog_203_freeresult();

/* the xdr functions */
extern bool_t xdr_join_203_argument();
extern bool_t xdr_leave_203_argument();
extern bool_t xdr_subscribe_203_argument();
extern bool_t xdr_unsubscribe_203_argument();
extern bool_t xdr_publish_203_argument();
extern bool_t xdr_update_203_argument();

#endif /* !_COMMUNICATE_H_RPCGEN */
